### PR TITLE
Add reverse scan to bigtable

### PR DESCRIPTION
**Pull request by Vincenthays**
I also need this [PR in liufuyang/googleapis](https://github.com/liufuyang/googleapis/pull/1) to finish

### CODE REVIEW

**Comment by Vincenthays** [comment]
I think we have to wait for Google to finish this feature 😢 
```
RpcError(Status { code: Unimplemented, message: "Client doesn't support reverse scans yet", metadata: MetadataMap { headers: {"x-goog-ext-9650773-bin": "DZR6nUA", "x-goog-ext-425905942-bin": "Cg5ldXJvcGUtd2VzdDEtZBINcHJvY2Vzc2luZy1jMQ", "endpoint-load-metrics-bin": "MdiLQaQlvHNAObVMuugNWck/QgsKABEAAACAUq8TQEn29+NKWiypPw", "grpc-server-stats-bin": "AAC+X2QXAAAAAA"} }, source: None })
```

**Comment by liufuyang** [comment]
Oh sure, thanks, we can merge this when we know the API is supported.

Just curious, wouldn't it normally be enough for the user to just sort the result again (or use some reversed index) to achieve the same?

**Comment by liufuyang** [comment]
Also notice this file is all generated, so later I can try to update the googleapis submodule and regenerate those rs files again.

Also, the Unimplemented RPC error above was from you testing against a real bigtable cluster?

**Comment by Vincenthays** [comment]
> Just curious, wouldn't it normally be enough for the user to just sort the result again (or use some reversed index) to achieve the same?

I plan to use it with the `rows_limit: 1`
`{prefix}aaaa....`
`many many lines`
`{prefix}zzzz....`
 I can retrieve either the first or last line, eliminating the need to download an excessive amount of data.

**Comment by Vincenthays** [comment]
> Also notice this file is all generated, so later I can try to update the googleapis submodule and regenerate those rs files again.
> 
> Also, the Unimplemented RPC error above was from you testing against a real bigtable cluster?

It was a real Bigtable cluster
Bigtable's documentation indicates that it currently only supported for Java clients, maybe there is a server side check happening
I will come back to this when it will be working
Thanks for the help

**Comment by liufuyang** [comment]
Aha, I see, so you do not know which one is the last key, so you want to do a range scan and get the last few (or one) values out? Interesting.

@igorbernstein2 Do you mind we ask you here about it? Is this "reverse" key only working for Java client or? :)

**Comment by liufuyang** [comment]
Please try with `bigtable_rs = "0.2.6"`, I will close tihs for now, thanks for the contribution though :)

**Pull request closed without merging**
