### PR TITLE
Fix cell merging edge-case

### PR DESCRIPTION
**Pull request by Antti**
According to BigTable's proto:

```
    // If this CellChunk is part of a chunked cell value and this is
    // not the final chunk of that cell, value_size will be set to the
    // total length of the cell value.  The client can use this size
    // to pre-allocate memory to hold the full cell value.
```

> and this is not the final chunk of that cell

We can use value_size to find a final chunk of a cell.

* Use `chunk.value_size` to find the final chunk of a cell
* Pre-allocate memory for the whole value

Should fix https://github.com/liufuyang/bigtable_rs/issues/7

### CODE REVIEW

**Comment by liufuyang** [comment]
I think this looks great and the code now seems even simpler. Thank you very much. I hope I could have time to actually bring some tests mentioned in #7 into the picture, let's see about that :)

**Comment by liufuyang** [comment]
I think this looks great and the code now seems even simpler. Thank you very much. I hope I could have time to actually bring some tests mentioned in #7 into the picture, let's see about that :)

**Comment by Antti** [comment]
Thank you for merging this! Having tests for this whole logic would be wonderful indeed.

**Comment by liufuyang** [comment]
@Antti I also released a new version `0.1.6` with some packages updated as well. You can try that if you want :)

**Comment by liufuyang** [comment]
@Antti I have [0.1.7](https://crates.io/crates/bigtable_rs) released with enhanced logic as it is heavily tested with google's official test file (done in PR #13 ). You can update the package to this newer version if you wish. The end-user API is untouched so it should work the same as before :)

**Pull request merged**
